### ISSUE TITLE
Plan to update the version of Node

### ISSUE THREAD

**Issue by dbloch3643** [benday-inc/deploy-ef-core-migration#328]
Github complains that the version of node (node12) is way out of date.  Any plans on updating?

**Comment by benday** [comment]
I'll take a look. It should be up to date but maybe I missed something.

**Comment by benday** [comment]
@dbloch3643 -- give this a go and see if it fixes the node warning.

https://github.com/benday-inc/deploy-ef-core-migration/releases/tag/v2

**Comment by benday** [comment]
Missed a spot.  I think I fixed it.  Check out version 2.1.

**Comment by dbloch3643** [comment]
Thank you, yes 2.1 is a winner.
